/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kazi;

import com.kazi.controllers.Car;
import com.kazi.controllers.Config;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
//import org.springframework.context.annotation.AnnotationConfigApplicationContext;


public class App {
    public static void main(String[] args) {
        ApplicationContext context = new AnnotationConfigApplicationContext(Config.class);

        Car lamboCar = context.getBean(Car.class);
        lamboCar.getCar();
    }
}
